services:
  # Backend API
  - type: web
    name: quran-verse-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn quran_backend:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  # Frontend React App  
  - type: web
    name: quran-verse-frontend
    env: static
    buildCommand: cd quran-front-end && npm install && npm run build
    staticPublishPath: ./quran-front-end/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://quran-verse-api.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html